standard/standard-engine

index.js

Without this, the defaulted `opts` parameter causes an NPE.

Forgive not having _config property on opts

---

bin/cmd.js

standard 5 is stricter about correct indentation in object literals

fix for standard 5

---

index.js

We are in the process of adding back the rule `padded-blocks` into `standard`. It was temporarily disabled because of a bug in eslint which now has been fixed.
This pull request makes sure that your coding style is compliant with the new version.
Please see feross/standard#170 for more info.

adhere to padded-blocks

---

index.js

Many projects have vendored files in `vendor/...` that need not to be checked.

Ignore vendored files

---

package.json

Just referencing `https` doesn't work with older versions of npm.
See example where it fails with npm v1.4.6 here: https://travis-ci.org/watson/async-state/builds/81012276
Using the `git+https` scheme instead should fix it.

Fix fetching of eslint with older npm versions

---

test/clone.js

I'm not sure why `Math.min` is used here (`Math.min(3.5) === 3.5`), I suspect this was meant to be `Math.floor` intead.

test/clone: fix integerization of parallel limit

---

package.json

This is a workaround until https://github.com/eslint/eslint/issues/4302 is fixed.

lock down eslint to 1.7.3 to fix space-in-parens

---

bin/cmd.js

remove prepended "Use" from tagline output

---

bin/cmd.js

When eslint rules are configured as a `1`, this will print the warning
message but still exit with code `0`.

Log warning messages when no errors are present

---

package.json

There is still a failing test, but its due to a bug fix in the `block-spacing` rule:
https://github.com/eslint/eslint/issues/4387
Basically, the rule was updated to require spaces for comments in blocks. This seems to affect repos that are doing multiline tricks... so it means they need to pad the comment with spaces:
```diff
var pkg = join(__dirname, 'test-package')
-var elfJS = function () {/*
+var elfJS = function () { /*
module.exports = function () {
console.log("i'm a elf")
}
-*/}.toString().split('\n').slice(1, -1).join()
+*/ }.toString().split('\n').slice(1, -1).join()
```
There were two projects that were throwing errors:
- `friends-swarm` which I just updated
- `fstream-npm` which we may want to disable in `standard-packages` for now since its failing.
Thoughts on this @feross? …

update eslint to 1.10.3

---

bin/cmd.js
index.js

So users can specify a custom plugin.
Works in `package.json`:
```json
{
"standard": {
"plugins": [ "my-plugin" ]
}
}
```
Or via command line option:
```
standard --plugin my-plugin
```
For user that need flowtype support, or whatever the new flavor of the
week will be in the future.
Fixes https://github.com/feross/standard/issues/386

Add --plugin option

---

index.js

So users can specify custom rules. For users that need to tweak one rule for their particular project.
Works in `package.json`:
```json
{
"standard": {
"rules": {
"semi": [2, "always"]
}
}
}
```
Fixes https://github.com/feross/standard/issues/367

Add rules option to package.json

---

bin/cmd.js
index.js

So users can specify custom rules.
Works in `package.json`:
```json
{
"standard": {
"env": {
"mocha": true
}
}
}
```
And the command line:
```
standard --env mocha test/*.js
```
For users that need to change the environment across their entire
project, or just for their tests (e.g. with mocha).
Fixes https://github.com/feross/standard/issues/371

Add --env option

---

index.js

Like .eslintrc files, .eslintignore files should not be used so that
`standard` behaves consistently wherever it is run.
Closes https://github.com/feross/standard/issues/500

Do not use .eslintignore files

---

bin/cmd.js
index.js

Add --fix option (uses eslint's --fix)

---

README.md
bin/cmd.js
index.js

Depends on PR: https://github.com/Flet/standard-engine/pull/119
There's no reason to limit this API to just .lintFiles. It works great
with .lintText too.
This actually paves a way for us to get rid of the built-in --format
option entirely, now that --fix works just as well.

Support auto-fixing source text (from --stdin and .lintText)

---

README.md
bin/cmd.js
index.js
test/clone.js

Depends on https://github.com/Flet/standard-engine/pull/119 and https://github.com/Flet/standard-engine/pull/120
`standard --fix` uses ESLint's built-in formatting functionality. The
nice thing about this vs. a formatter based on esformatter is that it
doesn't require maintaining a whole separate config file for a
different tool. It comes for free from the existing list of ESLint
rules. It also appears to be a lot more reliable than esformatter, with
ES6 support that's as good as ESLint's.
The esformatter integration was some of the trickiest code in this
package. I'm happy to finally be able to remove it.
This should be released as a new major version.

Remove formatter support (replaced by ESLint --fix)

---

bin/cmd.js
package.json

Not needed anymore, now that Node v4 is the minimum requirement for
standard-engine and ESLint.
Removes 3 total dependencies -- faster install!
Inspired by @nolanlawson's tweet: https://twitter.com/nolanlawson/status/766275330403205122

Improve install time, remove multiline dep

---

bin/cmd.js
index.js
package.json

These are not required in Node v4 anymore!
This removes a total of 3 modules from the tree.
Inspired by @nolanlawson's tweet:
https://twitter.com/nolanlawson/status/766275330403205122

Remove unneeded `xtend` and `defaults` dependencies

---

index.js
package.json

Running `standard` on a large codebase like [electron/electron](https://github.com/electron/electron) is now more than 2x faster on repeated runs, thanks to the ESLint cache feature!
- Before: 3.68s
- After: 1.59s
Fixes: https://github.com/feross/standard/issues/277
(I copied this code from the xo project.)

Add ESLint `cache` option

---

bin/cmd.js

Fixes: https://github.com/Flet/standard-engine/issues/129

Fix crash when 'stdin' and 'fix' options are used on code with no errors

---

README.md
index.js

Document `plugins` and `envs`, which can be specified in the project's
`package.json`. Change `global` to `globals` since that's what the code
prefers. Note the availability of the aliases.
Document that `cwd` may be provided to `lintText()` and `lintFiles()`,
and that this can cause additional options to be loaded from the
project's `package.json`. This is useful information for linter plugins
which may call this method.
Document that both the `ignore` and `files` globs are resolved relative
to the current working directory.
Document the full set of options, including aliases, and how the
`parser` option takes preference over the `parser` setting in the
project's `package.json`.
Support filename option in `lintText()`. Fixes #131.

Support filename option in lintText() and document all options

---

index.js

`standard-engine` has all the information it needs to resolve these
options. `deglob` shouldn't have to repeat the work of finding the
`package.json`.
This will make it easier to control the `ignore` globs in a custom
options parser, for which see
<https://github.com/Flet/standard-engine/pull/135>.
Requires https://github.com/Flet/deglob/pull/6 to be released and the
minimum version to be bumped.

wip! Resolve ignore options in standard-engine, not deglob

---

README.md

Hi, I just wrote a [package (o2team/standard-own)](https://github.com/o2team/standard-own) using `standard-engine`, it's like `standard` but with more customization, which allows people to tweak individual rules.

Add a new package named standard-own

---

README.md
index.js
package.json

This replaces find-root and pkg-config by pkg-conf.
pkg-conf can find config without throwing exceptions. It returns an
empty object by default, simplifying logic. And, usefully, it lets you
determine the path of the loaded `package.json` file.
pkg-config caches the JSON, though not the file resolution. I doubt the
caching has any measurable impact when it comes to `standard-engine` and
its use. Caching could be implemented on top of pkg-conf if necessary
though.
Adds support for a `parseOpts()` option in `options.js`. Fixes #132.

Support parseOpts() option

---

index.js

Fixes: https://github.com/Flet/standard-engine/issues/141
Explanation:
https://github.com/Flet/standard-engine/pull/146#issuecomment-272422326

Prevent package.json `parser` option from overriding explicit option

---

README.md
index.js

When we run `lintText` with `eslint-plugin-html` plugin, `opts.filename` should be specified or we will get wrong results.
**index.js**:
```node
var standard = require('standard')
var fs = require('fs')
fs.readFile('./index.html', 'utf8', function (err, html) {
standard.lintText(html, {
plugins: ['html'],
filename: 'index.html'
}, function (err, result) {
console.log(result.results[0])
})
standard.lintText(html, {
plugins: ['html']
}, function (err, result) {
console.log(result.results[0])
})
})
```
**index.html**:
```html
<html><head><title>haha</title></head><body>
<script>
var a= 1;
</script>
</body></html>
```
And the console:
```
{ filePath: '/Users/sam/Documents/tmp/test-eslint/index.html',
messages: 
[ { ruleId: 'no-unused-vars',
severity: 2,
message: '\'a\' is assigned a value but …
```

fix comments

---

README.md
bin/cmd.js
index.js
test/api.js

Fixes: https://github.com/Flet/standard-engine/issues/156
Before: `standardEngine.lintText(text, [opts], callback)`
After: `results = standardEngine.lintText(text, [opts])`
If an error occurs, an exception is thrown. Otherwise, a `results`
object is returned.

BREAKING: make lintText into a sync method

---

CHANGELOG.md
README.md
bin/cmd.js
index.js
test/api.js

Fixes: https://github.com/feross/standard/issues/807
- BREAKING: rename the synchronous `lintText` method to `lintTextSync`
- Add an asyncronous `lintText` method (that just calls `lintTextSync`
internally)
This effectively undoes the breaking change introduced in 6.0.0, making it safe to upgrade from `standard-engine` 5.x to 7.x without introducing any breaking changes.
But we also keep the new option to lint source text synchronously, just under a new `lintTextSync()` method. This is better than overloading `lintText` to behave differently depending on whether a callback is passed in or not, IMO.
Related: https://github.com/Flet/standard-engine/issues/156

BREAKING: rename the syncronous `lintText` method to `lintTextSync`

---

README.md

As proposed in #162 
I was not quite sure with how to present it, as there is no prior art to draw inspiration from. I have tried to keep it concise and to the point. :-)
----
> I see that you don't have any editor specific integrations listed, which makes sense as this project is not targeting "end-users", but I thought that it might be useful to add a note here for any other people that maintain big or small standard-engine linters. Either just through this issue, or maybe even as a note in the README file. I would love to send a PR if it's anything you'd be interested in. :-)

Add reference to standard-engine atom plugin

---

README.md
index.js

This option is required for project that use the `node_modules` style monorepo (Pouchdb, Cerebraljs).
Without this option the user has no control on default ignores.

add option to not use default ignores

---

README.md
index.js

1. Add an option { usePackageJson: false } to standard.lintText() that allows enabling/disabling taking package.json settings into account.
2. Change the default back to what it was in 7.0.0, which is to take package.json into account by default. Ignoring package.json settings is a breaking change that should not have been released in 7.1.0.
See: https://github.com/standard/standard-engine/pull/166#issuecomment-366482023

BREAKING: Add { usePackageJson: false } option, set default to `true`

---

index.js
package.json
test/api.js
test/lib/standard-cmd.js

[ ] Bug fix
[x] Other, please explain: lint update
I started using object shorthand for properties, that is, I changed `eslint: eslint` to `eslint`.
https://github.com/standard/eslint-config-standard/pull/166
The three lines changed 😅 
-----
Compatibility: This is supported on Node.js >=4, and we are using `Object.assign` which also became available in that version ✅

Use object shorthand for properties

---

.npmrc
.travis.yml
README.md
package.json

[ ] Bug fix
[x] Other, please explain: lots of cleanup & small fixes, see each commit for full details
- Disable package-lock file
- This file is not applicable for libraries
- Cleanup package metadata
- Update repository to new location
- Use repository shorthand
- Sort with `npx sort-package-json`
- Bump deglob & minimist dependencies
- Bump all dev-dependencies
- Also switch from `*` to `^`
- Test on supported Node.js versions
- 8.10
- 10
- 12
- 14
- Fix linting errors in readme
#213 #218 
everything 😅

Cleanup & small fixes

---

bin/cmd.js

This allows a downstream project like `tsdocstandard` to subclass the `Linter`
[ ] Bug fix
[X] New feature
Allow passing in a custom linter object to `cli()`

Allow passing in a custom linter to `cli`

---

README.md
bin/cmd.js

The documents say that "bundle.js" is ignored by default, but actually it is not (anymore). https://github.com/standard/standard-engine/commit/1319c5b4d6b39eecf909a7072ae92eabe36e0213
[x] Documentation update
[ ] Bug fix
Removed `bundle.js` from the list of default ignored files in `README.md` and `standard --help`.
https://github.com/standard/standard/issues/743

[docs] Remove bundle.js from the list of default ignored files

---

index.js
package.json

[ ] Bug fix
[x] New feature
Instead of setting the cacheLocation to a directory in the user `$HOME`, this PR now respects the [XDG Basedir Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (specifically the `XDG_CACHE_HOME` environment variable).
fixes https://github.com/standard/standard/issues/1501
The XDG Basedir spec states that `XDG_CACHE_HOME` should be used (if set) to determine where to write cache files. It is recommended and conventional that tools create …

Cache directory respects XDG_CACHE_HOME (basedir spec)

---

index.js
package.json
test/clone.js

[x] Bug fix
BREAKING: Use eslint for file ignoring; remove deblog
Ignore patterns should follow the .gitignore format rather than the `glob` pattern. So, you can use dir/ instead of dir/** now. There may be subtle differences in behavior.
Fixes: #226
Fixes: https://github.com/standard/standard/issues/1333
Fixes: https://github.com/standard/standard/issues/1117
Fixes: https://github.com/standard/standard/issues/1023
Fixes: https://github.com/standard/standard/issues/1384

BREAKING: Use eslint for pattern ignoring; remove deglob

---

README.md
index.js

Allow all options to be passed into lintText / lintFiles, or specified in the package.json:
- New: Add `extensions` option
- New: Add `noDefaultExtensions` option
- New: Allow `ignore` to be passed in to lintText / lintFiles
- New: Allow `noDefaultIgnore` to be passed in to lintText / lintFiles

Add `extensions` and `noDefaultExtensions` options; Allow all options to be passed into lintText / lintFiles, or specified in the package.json

---

.github/dependabot.yml
.github/workflows/nodejs.yml
.travis.yml
README.md

- Add `.github/dependabot.yml`
- Add `.github/workflows/nodejs.yml`
- Delete `.travis.yml`
- Update `README` with the new badge
We should remove the stale branches from the old Greenkeeper bot https://github.com/standard/standard-engine/branches/stale once this has been merged.

ci: add dependabot + change Travis to GitHub actions

---

README.md
bin/cmd.js
test/clone.js

As discussed in https://github.com/standard/standard/issues/1585
This PR delete the `--verbose` flag.

feat: make `--verbose` the default 

---

README.md
bin/cmd.js
index.js
lib/resolve-eslint-config.js
package.json
test/api.js
tsconfig.json

[ ] Bug fix
[x] Other, please explain: To make #234 simpler to solve
The main changes:
1. I extended the JSDoc types + added a validation of them using the TypeScript cli utility – this to better ensure that the public API contract doesn't get broken when I, @Divlo or someone else new to the code contributes.
2. In the process of adding the types I found that `parseOpts()` was a bit all over the place and unlike its name was actually mainly focused on simply constructing the needed ESLint Config. I therefore revamped it to be fully focused on that + extracted it into a file of its own to make both it and the main file shorter …

Add more JSDoc annotations + validate them and refactor to make them clearer

---

package.json

As the minor versions of TypeScript can cause type issues and 4.4 currently does here
[x] Bug fix
I locked the minor version of our typescript dev-dependency
It ensures that we don't get premature errors from an upgrade to eg. typescript 4.4, which we currently are getting, making for a poor contributor experience:
Not really

Require TypeScript 4.3 until we update

---

.github/workflows/nodejs.yml
package.json
tsconfig.json

BREAKING CHANGE: Minimum supported Node.js version >= 12.0.0

chore: drop support for Node.js v10

---

README.md
bin/cmd.js
index.js
test/api.js
test/lib/standard-cmd.js

[ ] Bug fix
[x] New feature
Before:
```js
const { linter } = require('standard-engine')
```
After:
```js
const { Linter } = require('standard-engine')
```
Fixes #250 
**BREAKING CHANGES** introduced by this PR:
- Export is now called `Linter`, not `linter`
- Calling `Linter()` instead of `new Linter()` doesn't work anymore.

feat: usage of ES6 class syntax

---

bin/cmd.js

[x] Bug fix
`standard-engine` is being used not only for `standard` itself but also for other engines like [ts-standard](https://github.com/toddbluhm/ts-standard), [happiness](https://github.com/JedWatson/happiness), etc.
That being said, it makes sense to not include specific things related to `standard` only.
This PR remove the mention of [standardjs.com](https://standardjs.com) in a warning message.

fix(cli): warning message mention homepage

---

.github/dependabot.yml
.github/workflows/lint.yml
.github/workflows/nodejs.yml
.gitignore
CHANGELOG.md
README.md
bin/cmd.js
index.js
lib/resolve-eslint-config.js
lib/utils.js
package.json
test/api.js
test/clone.js
test/lib/standard-cmd.js
test/utils-ensure-array.js
test/utils-ensure-string-array-value.js
test/utils-string-array-to-obj.js
tsconfig.json

Fixes #234
Just throwing this out here, not thoroughly tested, but all tests pass + all types are okay
Things remaining:

Initial port to new ESLint API

---

README.md

[x] Documentation update
[ ] Bug fix
- Update link to `ts-standard` to the `standard` org
- As of v15, we now support ESLint >= 7.0.0 (not anymore >= 1.0.0)
- Fix `eslint.configFile` in `options.js` instead it should be now `eslint.overrideConfigFile`

docs(readme): update few quirks

---

index.js

This ensures that fixes are written before resolving.
Without this, the file may be in a weird state if consumed right after calling `lintFiles()` (e.g. reading the files right after calling `lintFiles()` would return an empty string, stat would show a zero-sized file).
[x] Bug fix
Added `await` to `this.eslint.ESLint.outputFixes(result)` to ensure the fixed files are written before `lintFiles()` returns.
Under the hood, [`ESLint.outputFixes()`](https://github.com/eslint/eslint/blob/v8.13.0/lib/eslint/eslint.js#L472) is an async function that awaits on a promisified `fs.writeFile()`. 
**Which issue (if …

lintFiles() to await on ESLint.outputFixes()
